### ISSUE TITLE
add kotlin code snippets

### ISSUE THREAD

**Issue by NikkyAI** [gradle-guides/writing-gradle-plugins#11] opened 2018-10-21 11:39 UTC
pretty self explainatory, with gradle 5 coming up and kotlin-dsl 1.0 having the official guides updated to reflect that would be nice

**Comment by jlstrater** [comment] 2019-02-14 11:44
closing as a duplicate of https://github.com/gradle/guides/issues/191

**Closed by jlstrater** 2019-02-14 11:44 UTC
